# Generated by Django 3.1.7 on 2021-03-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('web_url', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=260)),
            ],
            options={
                'db_table': 'sites_vacation',
            },
        ),
    ]
